import { Conjunto, Residente, CarteraExpensas, PQRSTicket } from '../src/types/index.js';

export const CONJUNTOS_DATA: Conjunto[] = [
  {
    id: 'conjunto-1',
    nombre: 'Conjunto Residencial Torres del Parque P.H.',
    nit: '900.845.120-3',
    direccion: 'Carrera 7 # 128 - 45',
    ciudad: 'Bogotá D.C.',
    totalUnidades: 160,
    administrador: 'Dra. Claudia Marcela Carvajal',
    telefonoAdmin: '(+57) 601 745 8890',
    emailAdmin: 'administracion@torresdelparqueph.com',
  },
  {
    id: 'conjunto-2',
    nombre: 'Condominio Bosques de San Rafael',
    nit: '901.332.908-1',
    direccion: 'Calle 10 Sur # 35 - 80',
    ciudad: 'Medellín',
    totalUnidades: 120,
    administrador: 'Ing. Rodrigo Henao',
    telefonoAdmin: '(+57) 604 444 1234',
    emailAdmin: 'admin@bosquesdesanrafael.com',
  },
  {
    id: 'conjunto-3',
    nombre: 'Edificio Portal de Alameda',
    nit: '890.112.540-9',
    direccion: 'Avenida 6 Norte # 24 - 15',
    ciudad: 'Cali',
    totalUnidades: 80,
    administrador: 'Dra. Patricia Valderrama',
    telefonoAdmin: '(+57) 602 660 9988',
    emailAdmin: 'contacto@portaldealameda.com',
  },
];

export const RESIDENTES_DATA: Residente[] = [
  // --- CONJUNTO 1: Torres del Parque (Bogotá) ---
  {
    id: 'res-1',
    conjuntoId: 'conjunto-1',
    cedula: '1018456789',
    nombre: 'Carlos Andrés Mendoza',
    email: 'carlos.mendoza@email.com',
    telefono: '315 890 1234',
    torre: 'Torre 2',
    apto: '401',
    tipo: 'Propietario',
    alicuota: 0.85,
    mascotas: 'No registra mascotas',
    vehiculoPlaca: 'BKL-782',
    parqueadero: 'Sótano 1 - Espacio 42',
  },
  {
    id: 'res-2',
    conjuntoId: 'conjunto-1',
    cedula: '52987654',
    nombre: 'María Fernanda Gómez',
    email: 'maria.gomez@email.com',
    telefono: '320 456 7890',
    torre: 'Torre 1',
    apto: '203',
    tipo: 'Propietaria',
    alicuota: 0.95,
    mascotas: '1 Gato criollo (Milo)',
    vehiculoPlaca: 'FRW-419',
    parqueadero: 'Plataforma 1 - Espacio 15',
  },
  {
    id: 'res-3',
    conjuntoId: 'conjunto-1',
    cedula: '80321456',
    nombre: 'Juan David Restrepo',
    email: 'juan.restrepo@email.com',
    telefono: '311 234 5678',
    torre: 'Torre 3',
    apto: '502',
    tipo: 'Arrendatario',
    alicuota: 0.78,
    mascotas: '1 Canino Golden Retriever (Max)',
    vehiculoPlaca: 'MZN-105',
    parqueadero: 'Sótano 2 - Espacio 88',
  },
  {
    id: 'res-4',
    conjuntoId: 'conjunto-1',
    cedula: '1020789123',
    nombre: 'Laura Sofía Sánchez',
    email: 'claudiamarcelacarvajal27@gmail.com',
    telefono: '315 645 8744',
    torre: 'Torre 4',
    apto: '101',
    tipo: 'Propietaria',
    alicuota: 1.05,
    mascotas: '1 perro Pug',
    vehiculoPlaca: 'QWE-999',
    parqueadero: 'Sótano 1 - Espacio 12',
  },
];

export const CARTERA_DATA: Record<string, CarteraExpensas> = {
  // Conjunto 1 (Los Sauces / Torres del Parque)
  '1020789123': {
    id: 'cart-4',
    residenteId: 'res-4',
    cedula: '1020789123',
    mesPeriodo: 'Septiembre 2026',
    cuotaOrdinaria: 420000,
    cuotaExtraordinaria: 50000,
    totalMora: 200000,
    mesesMora: 1,
    interesesMora: 12000,
    descuentoProntoPago: 0,
    totalPagar: 682000,
    fechaLimiteDescuento: '10 de Septiembre de 2026',
    fechaVencimiento: '30 de Septiembre de 2026',
    estado: 'Acuerdo de pago',
    alicuota: 1.05,
    historialPagos: [
      { id: 'p-laura-1', fecha: '05/08/2026', concepto: 'Administración Agosto 2026', valor: 420000, referencia: 'PSE-Supabase-OK', estado: 'Aprobado' },
    ],
  },
  '1018456789': {
    id: 'cart-1',
    residenteId: 'res-1',
    cedula: '1018456789',
    mesPeriodo: 'Septiembre 2026',
    cuotaOrdinaria: 380000,
    cuotaExtraordinaria: 0,
    totalMora: 0,
    mesesMora: 0,
    interesesMora: 0,
    descuentoProntoPago: 38000,
    totalPagar: 342000,
    fechaLimiteDescuento: '10 de Septiembre de 2026',
    fechaVencimiento: '30 de Septiembre de 2026',
    estado: 'Al día',
    alicuota: 0.85,
    historialPagos: [
      { id: 'p1', fecha: '08/08/2026', concepto: 'Administración Agosto 2026', valor: 342000, referencia: 'PSE-889021', estado: 'Aprobado' },
      { id: 'p2', fecha: '05/07/2026', concepto: 'Administración Julio 2026', valor: 342000, referencia: 'PSE-774123', estado: 'Aprobado' },
    ],
  },
  '52987654': {
    id: 'cart-2',
    residenteId: 'res-2',
    cedula: '52987654',
    mesPeriodo: 'Septiembre 2026',
    cuotaOrdinaria: 410000,
    cuotaExtraordinaria: 50000,
    totalMora: 820000,
    mesesMora: 2,
    interesesMora: 48500,
    descuentoProntoPago: 0,
    totalPagar: 1328500,
    fechaLimiteDescuento: 'No aplica (En mora)',
    fechaVencimiento: 'Inmediata',
    estado: 'En mora',
    alicuota: 0.95,
    historialPagos: [
      { id: 'p4', fecha: '12/06/2026', concepto: 'Administración Junio 2026 (Parcial)', valor: 250000, referencia: 'TRANSF-902', estado: 'Aprobado' },
    ],
  },
  '80321456': {
    id: 'cart-3',
    residenteId: 'res-3',
    cedula: '80321456',
    mesPeriodo: 'Septiembre 2026',
    cuotaOrdinaria: 350000,
    cuotaExtraordinaria: 0,
    totalMora: 0,
    mesesMora: 0,
    interesesMora: 0,
    descuentoProntoPago: 35000,
    totalPagar: 315000,
    fechaLimiteDescuento: '10 de Septiembre de 2026',
    fechaVencimiento: '30 de Septiembre de 2026',
    estado: 'Al día',
    alicuota: 0.78,
    historialPagos: [
      { id: 'p5', fecha: '04/08/2026', concepto: 'Administración Agosto 2026', valor: 315000, referencia: 'PSE-901844', estado: 'Aprobado' },
    ],
  },
};

export const INITIAL_TICKETS: PQRSTicket[] = [
  // Tickets exclusivos de Conjunto 1 (Bogotá)
  {
    id: 'tk-101',
    codigo: 'PQRS-2026-089',
    conjuntoId: 'conjunto-1',
    residenteId: 'res-1',
    residenteNombre: 'Carlos Andrés Mendoza',
    unidad: 'Torre 2 Apto 401',
    categoria: 'Mantenimiento / Daños',
    descripcion: 'Filtración de agua proveniente de la jardinera de la terraza del piso 5 hacia el techo del pasillo frente al apto 401.',
    prioridad: 'Alta',
    estado: 'En Revisión',
    slaHoras: 24,
    fechaCreacion: '2026-09-05 14:30',
    respuestaAdmin: 'Personal de plomería y mantenimiento programado para inspección el 07 de Septiembre a las 10:00 a.m.',
  },
  {
    id: 'tk-102',
    codigo: 'PQRS-2026-092',
    conjuntoId: 'conjunto-1',
    residenteId: 'res-2',
    residenteNombre: 'María Fernanda Gómez',
    unidad: 'Torre 1 Apto 203',
    categoria: 'Expensas y Cartera',
    descripcion: 'Solicitud formal de propuesta de acuerdo de pago para diferir cuotas de julio y agosto.',
    prioridad: 'Media',
    estado: 'Radicado',
    slaHoras: 72,
    fechaCreacion: '2026-09-06 09:15',
  },
  {
    id: 'tk-103',
    codigo: 'PQRS-2026-095',
    conjuntoId: 'conjunto-1',
    residenteId: 'res-4',
    residenteNombre: 'Laura Sofía Sánchez',
    unidad: 'Torre 4 Apto 101',
    categoria: 'Ruido y Convivencia',
    descripcion: 'Ruido excesivo y música a alto volumen en horas de la madrugada en apartamento del piso superior.',
    prioridad: 'Media',
    estado: 'Radicado',
    slaHoras: 48,
    fechaCreacion: '2026-09-07 11:20',
  },
];
